// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An agent acts as the fundamental building block that provides instructions to
/// the Large Language Model (LLM) for executing specific tasks.
public struct Agent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The unique identifier of the agent.
  /// Format: `projects/{project}/locations/{location}/apps/{app}/agents/{agent}`
  public var name: Swift.String = Swift.String()

  /// Required. Display name of the agent.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Human-readable description of the agent.
  public var description: Swift.String = Swift.String()

  /// Optional. Configurations for the LLM model.
  public var modelSettings: ModelSettings? = nil

  /// Optional. Instructions for the LLM model to guide the agent's behavior.
  public var instruction: Swift.String = Swift.String()

  /// Optional. List of available tools for the agent.
  /// Format: `projects/{project}/locations/{location}/apps/{app}/tools/{tool}`
  public var tools: [Swift.String] = []

  /// Optional. List of child agents in the agent tree.
  /// Format: `projects/{project}/locations/{location}/apps/{app}/agents/{agent}`
  public var childAgents: [Swift.String] = []

  /// Optional. The callbacks to execute before the agent is called.
  /// The provided callbacks are executed sequentially in the exact order they
  /// are given in the list. If a callback returns an overridden response,
  /// execution stops and any remaining callbacks are skipped.
  public var beforeAgentCallbacks: [Callback] = []

  /// Optional. The callbacks to execute after the agent is called.
  /// The provided callbacks are executed sequentially in the exact order they
  /// are given in the list. If a callback returns an overridden response,
  /// execution stops and any remaining callbacks are skipped.
  public var afterAgentCallbacks: [Callback] = []

  /// Optional. The callbacks to execute before the model is called. If there are
  /// multiple calls to the model, the callback will be executed multiple times.
  /// The provided callbacks are executed sequentially in the exact order they
  /// are given in the list. If a callback returns an overridden response,
  /// execution stops and any remaining callbacks are skipped.
  public var beforeModelCallbacks: [Callback] = []

  /// Optional. The callbacks to execute after the model is called. If there are
  /// multiple calls to the model, the callback will be executed multiple times.
  /// The provided callbacks are executed sequentially in the exact order they
  /// are given in the list. If a callback returns an overridden response,
  /// execution stops and any remaining callbacks are skipped.
  public var afterModelCallbacks: [Callback] = []

  /// Optional. The callbacks to execute before the tool is invoked. If there are
  /// multiple tool invocations, the callback will be executed multiple times.
  /// The provided callbacks are executed sequentially in the exact order they
  /// are given in the list. If a callback returns an overridden response,
  /// execution stops and any remaining callbacks are skipped.
  public var beforeToolCallbacks: [Callback] = []

  /// Optional. The callbacks to execute after the tool is invoked. If there are
  /// multiple tool invocations, the callback will be executed multiple times.
  /// The provided callbacks are executed sequentially in the exact order they
  /// are given in the list. If a callback returns an overridden response,
  /// execution stops and any remaining callbacks are skipped.
  public var afterToolCallbacks: [Callback] = []

  /// Output only. Timestamp when the agent was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Timestamp when the agent was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. List of guardrails for the agent.
  /// Format:
  /// `projects/{project}/locations/{location}/apps/{app}/guardrails/{guardrail}`
  public var guardrails: [Swift.String] = []

  /// Etag used to ensure the object hasn't changed during a read-modify-write
  /// operation. If the etag is empty, the update will overwrite any concurrent
  /// changes.
  public var etag: Swift.String = Swift.String()

  /// Optional. List of toolsets for the agent.
  public var toolsets: [Agent.AgentToolset] = []

  /// Output only. If the agent is generated by the LLM assistant, this field
  /// contains a descriptive summary of the generation.
  public var generatedSummary: Swift.String = Swift.String()

  /// Optional. Agent transfer rules.
  /// If multiple rules match, the first one in the list will be used.
  public var transferRules: [TransferRule] = []

  /// Output only. Misconfigurations or errors in the agent that may affect agent
  /// quality.
  public var validationErrors: [Swift.String] = []

  /// The type of agent.
  public var agentType: OneOf_AgentType? = nil

  /// Initialize a new instance of `Agent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Agent().with { $0.llmAgent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case llmAgent = "llmAgent"
    case remoteDialogflowAgent = "remoteDialogflowAgent"
    case name = "name"
    case displayName = "displayName"
    case description = "description"
    case modelSettings = "modelSettings"
    case instruction = "instruction"
    case tools = "tools"
    case childAgents = "childAgents"
    case beforeAgentCallbacks = "beforeAgentCallbacks"
    case afterAgentCallbacks = "afterAgentCallbacks"
    case beforeModelCallbacks = "beforeModelCallbacks"
    case afterModelCallbacks = "afterModelCallbacks"
    case beforeToolCallbacks = "beforeToolCallbacks"
    case afterToolCallbacks = "afterToolCallbacks"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case guardrails = "guardrails"
    case etag = "etag"
    case toolsets = "toolsets"
    case generatedSummary = "generatedSummary"
    case transferRules = "transferRules"
    case validationErrors = "validationErrors"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.modelSettings = try container.decodeIfPresent(ModelSettings.self, forKey: .modelSettings)
    self.instruction = try container.decode(Swift.String.self, forKey: .instruction)
    self.tools = try container.decode([Swift.String].self, forKey: .tools)
    self.childAgents = try container.decode([Swift.String].self, forKey: .childAgents)
    self.beforeAgentCallbacks = try container.decode([Callback].self, forKey: .beforeAgentCallbacks)
    self.afterAgentCallbacks = try container.decode([Callback].self, forKey: .afterAgentCallbacks)
    self.beforeModelCallbacks = try container.decode([Callback].self, forKey: .beforeModelCallbacks)
    self.afterModelCallbacks = try container.decode([Callback].self, forKey: .afterModelCallbacks)
    self.beforeToolCallbacks = try container.decode([Callback].self, forKey: .beforeToolCallbacks)
    self.afterToolCallbacks = try container.decode([Callback].self, forKey: .afterToolCallbacks)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.guardrails = try container.decode([Swift.String].self, forKey: .guardrails)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)
    self.toolsets = try container.decode([Agent.AgentToolset].self, forKey: .toolsets)
    self.generatedSummary = try container.decode(Swift.String.self, forKey: .generatedSummary)
    self.transferRules = try container.decode([TransferRule].self, forKey: .transferRules)
    self.validationErrors = try container.decode([Swift.String].self, forKey: .validationErrors)

    var agentType: OneOf_AgentType? = nil
    let agentTypeCheckAndSet = {
      if agentType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'agentType'"))
      }
      agentType = $0
    }
    if let llmAgent = try container.decodeIfPresent(Agent.LlmAgent?.self, forKey: .llmAgent) {
      try agentTypeCheckAndSet(.llmAgent(llmAgent))
    }
    if let remoteDialogflowAgent = try container.decodeIfPresent(
      Agent.RemoteDialogflowAgent?.self, forKey: .remoteDialogflowAgent)
    {
      try agentTypeCheckAndSet(.remoteDialogflowAgent(remoteDialogflowAgent))
    }
    self.agentType = agentType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.modelSettings, forKey: .modelSettings)
    try container.encode(self.instruction, forKey: .instruction)
    try container.encode(self.tools, forKey: .tools)
    try container.encode(self.childAgents, forKey: .childAgents)
    try container.encode(self.beforeAgentCallbacks, forKey: .beforeAgentCallbacks)
    try container.encode(self.afterAgentCallbacks, forKey: .afterAgentCallbacks)
    try container.encode(self.beforeModelCallbacks, forKey: .beforeModelCallbacks)
    try container.encode(self.afterModelCallbacks, forKey: .afterModelCallbacks)
    try container.encode(self.beforeToolCallbacks, forKey: .beforeToolCallbacks)
    try container.encode(self.afterToolCallbacks, forKey: .afterToolCallbacks)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.guardrails, forKey: .guardrails)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.toolsets, forKey: .toolsets)
    try container.encode(self.generatedSummary, forKey: .generatedSummary)
    try container.encode(self.transferRules, forKey: .transferRules)
    try container.encode(self.validationErrors, forKey: .validationErrors)

    if let choice = self.agentType {
      switch choice {
      case .llmAgent(let value):
        try container.encode(value, forKey: .llmAgent)
      case .remoteDialogflowAgent(let value):
        try container.encode(value, forKey: .remoteDialogflowAgent)
      }
    }
  }

  /// Default agent type. The agent uses instructions and callbacks specified in
  /// the agent to perform the task using a large language model.
  public struct LlmAgent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `LlmAgent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LlmAgent().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.Agent.LlmAgent"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The agent which will transfer execution to a remote
  /// [Dialogflow
  /// CX](https://docs.cloud.google.com/dialogflow/cx/docs/concept/agent) agent.
  /// The Dialogflow agent will process subsequent user queries until the session
  /// ends or flow ends, and the control is transferred back to the parent CES
  /// agent.
  public struct RemoteDialogflowAgent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The
    /// [Dialogflow](https://docs.cloud.google.com/dialogflow/cx/docs/concept/agent)
    /// agent resource name.
    /// Format: `projects/{project}/locations/{location}/agents/{agent}`
    public var agent: Swift.String = Swift.String()

    /// Optional. The flow ID of the flow in the Dialogflow agent.
    public var flowId: Swift.String = Swift.String()

    /// Optional. The environment ID of the Dialogflow agent to be used for the
    /// agent execution. If not specified, the draft environment will be used.
    public var environmentId: Swift.String = Swift.String()

    /// Optional. The mapping of the app variables names to the Dialogflow
    /// session parameters names to be sent to the Dialogflow agent as input.
    public var inputVariableMapping: [Swift.String: Swift.String] = [:]

    /// Optional. The mapping of the Dialogflow session parameters names to the
    /// app variables names to be sent back to the CES agent after the Dialogflow
    /// agent execution ends.
    public var outputVariableMapping: [Swift.String: Swift.String] = [:]

    /// Optional. Indicates whether to respect the message-level interruption
    /// settings configured in the Dialogflow agent.
    ///
    /// * If false: all response messages from the Dialogflow agent follow the
    /// app-level barge-in settings.
    /// * If true: only response messages with
    /// [`allow_playback_interruption`](https://docs.cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.dialogflow.cx.v3#text)
    /// set to true will be interruptable, all other messages follow the
    /// app-level barge-in settings.
    public var respectResponseInterruptionSettings: Swift.Bool = Swift.Bool()

    /// Optional. The name of the variable that contains the language code to be
    /// used for the Dialogflow session. If unspecified, the default language
    /// code of the Dialogflow agent will be used.
    public var languageCodeVariable: Swift.String = Swift.String()

    /// Initialize a new instance of `RemoteDialogflowAgent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RemoteDialogflowAgent().with { $0.agent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.Agent.RemoteDialogflowAgent"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A toolset with a selection of its tools.
  public struct AgentToolset: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the toolset.
    /// Format:
    /// `projects/{project}/locations/{location}/apps/{app}/toolsets/{toolset}`
    public var toolset: Swift.String = Swift.String()

    /// Optional. The tools IDs to filter the toolset.
    public var toolIds: [Swift.String] = []

    /// Initialize a new instance of `AgentToolset`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AgentToolset().with { $0.toolset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.Agent.AgentToolset"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The type of agent.
  public enum OneOf_AgentType: Codable, Equatable, Sendable {
    /// Optional. The default agent type.
    indirect case llmAgent(Agent.LlmAgent?)
    /// Optional. The remote
    /// [Dialogflow](https://cloud.google.com/dialogflow/cx/docs/concept/console-conversational-agents)
    /// agent to be used for the agent execution. If this field is set, all other
    /// agent level properties will be ignored.
    ///
    /// Note: If the Dialogflow agent is in a different project from the app, you
    /// should grant `roles/dialogflow.client` to the CES service agent
    /// `service-<PROJECT-NUMBER>@gcp-sa-ces.iam.gserviceaccount.com`.
    indirect case remoteDialogflowAgent(Agent.RemoteDialogflowAgent?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.Agent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
