// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents a distinct capability or function that an agent can perform.
public struct AgentSkill: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A unique identifier for the agent's skill.
  public var id: Swift.String = Swift.String()

  /// Required. A human-readable name for the skill.
  public var name: Swift.String = Swift.String()

  /// Required. A detailed description of the skill.
  public var description: Swift.String = Swift.String()

  /// Required. A set of keywords describing the skill's capabilities.
  public var tags: [Swift.String] = []

  /// Example prompts or scenarios that this skill can handle.
  public var examples: [Swift.String] = []

  /// The set of supported input media types for this skill, overriding the
  /// agent's defaults.
  public var inputModes: [Swift.String] = []

  /// The set of supported output media types for this skill, overriding the
  /// agent's defaults.
  public var outputModes: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AgentSkill`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AgentSkill().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let id = CodingKeys(stringValue: "id")
    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let tags = CodingKeys(stringValue: "tags")
    static let examples = CodingKeys(stringValue: "examples")
    static let inputModes = CodingKeys(stringValue: "inputModes")
    static let outputModes = CodingKeys(stringValue: "outputModes")

    static let _knownKeys: Set<Swift.String> = [
      "id",
      "name",
      "description",
      "tags",
      "examples",
      "inputModes",
      "outputModes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .examples) {
      self.examples = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .inputModes) {
      self.inputModes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .outputModes) {
      self.outputModes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.examples, forKey: .examples)
    try container.encode(self.inputModes, forKey: .inputModes)
    try container.encode(self.outputModes, forKey: .outputModes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.AgentSkill"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
