// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration for the ambient sound to be played with the synthesized agent
/// response, to enhance the naturalness of the conversation.
public struct AmbientSoundConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Volume gain (in dB) of the normal native volume supported by
  /// ambient noise, in the range [-96.0, 16.0]. If unset, or set to a value of
  /// 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB)
  /// will play at approximately half the amplitude of the normal native signal
  /// amplitude. A value of +6.0 (dB) will play at approximately twice the
  /// amplitude of the normal native signal amplitude. We strongly recommend not
  /// to exceed +10 (dB) as there's usually no effective increase in loudness for
  /// any value greater than that.
  public var volumeGainDb: Swift.Double = Swift.Double()

  /// Ambient noise to be played with the synthesized agent response, to
  /// enhance the naturalness of the conversation.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `AmbientSoundConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AmbientSoundConfig().with { $0.prebuiltAmbientNoise = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case prebuiltAmbientNoise = "prebuiltAmbientNoise"
    case gcsUri = "gcsUri"
    case prebuiltAmbientSound = "prebuiltAmbientSound"
    case volumeGainDb = "volumeGainDb"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.volumeGainDb = try container.decode(Swift.Double.self, forKey: .volumeGainDb)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let prebuiltAmbientNoise = try container.decodeIfPresent(
      AmbientSoundConfig.PrebuiltAmbientNoise.self, forKey: .prebuiltAmbientNoise)
    {
      try sourceCheckAndSet(.prebuiltAmbientNoise(prebuiltAmbientNoise))
    }
    if let gcsUri = try container.decodeIfPresent(Swift.String.self, forKey: .gcsUri) {
      try sourceCheckAndSet(.gcsUri(gcsUri))
    }
    if let prebuiltAmbientSound = try container.decodeIfPresent(
      Swift.String.self, forKey: .prebuiltAmbientSound)
    {
      try sourceCheckAndSet(.prebuiltAmbientSound(prebuiltAmbientSound))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.volumeGainDb, forKey: .volumeGainDb)

    if let choice = self.source {
      switch choice {
      case .prebuiltAmbientNoise(let value):
        try container.encode(value, forKey: .prebuiltAmbientNoise)
      case .gcsUri(let value):
        try container.encode(value, forKey: .gcsUri)
      case .prebuiltAmbientSound(let value):
        try container.encode(value, forKey: .prebuiltAmbientSound)
      }
    }
  }

  /// Prebuilt ambient noise.
  public enum PrebuiltAmbientNoise: Codable, Equatable, Sendable {
    /// Not specified.
    case unspecified
    /// Ambient noise of a retail store.
    case retailStore
    /// Ambient noise of a convention hall.
    case conventionHall
    /// Ambient noise of a street.
    case outdoor
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .retailStore: return 1
      case .conventionHall: return 2
      case .outdoor: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PREBUILT_AMBIENT_NOISE_UNSPECIFIED"
      case .retailStore: return "RETAIL_STORE"
      case .conventionHall: return "CONVENTION_HALL"
      case .outdoor: return "OUTDOOR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PREBUILT_AMBIENT_NOISE_UNSPECIFIED": self = .unspecified
      case "RETAIL_STORE": self = .retailStore
      case "CONVENTION_HALL": self = .conventionHall
      case "OUTDOOR": self = .outdoor
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .retailStore
      case 2: self = .conventionHall
      case 3: self = .outdoor
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .retailStore: return try container.encode(1)
      case .conventionHall: return try container.encode(2)
      case .outdoor: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Ambient noise to be played with the synthesized agent response, to
  /// enhance the naturalness of the conversation.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Optional. Deprecated: `prebuilt_ambient_noise` is deprecated in favor of
    /// `prebuilt_ambient_sound`.
    @available(*, deprecated)
    case prebuiltAmbientNoise(AmbientSoundConfig.PrebuiltAmbientNoise)
    /// Optional. Ambient noise as a mono-channel, 16kHz WAV file stored in
    /// [Cloud Storage](https://cloud.google.com/storage).
    ///
    /// Note: Please make sure the CES service agent
    /// `service-<PROJECT-NUMBER>@gcp-sa-ces.iam.gserviceaccount.com` has
    /// `storage.objects.get` permission to the Cloud Storage object.
    case gcsUri(Swift.String)
    /// Optional. Name of the prebuilt ambient sound.
    /// Valid values are:
    /// - "coffee_shop"
    /// - "keyboard"
    /// - "keypad"
    /// - "hum"
    /// - "office_1"
    /// - "office_2"
    /// - "office_3"
    /// - "room_1"
    /// - "room_2"
    /// - "room_3"
    /// - "room_4"
    /// - "room_5"
    /// - "air_conditioner"
    case prebuiltAmbientSound(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.AmbientSoundConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
