// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A snapshot of the app.
public struct AppSnapshot: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The basic settings for the app.
  public var app: App? = nil

  /// Optional. List of agents in the app.
  public var agents: [Agent] = []

  /// Optional. List of tools in the app.
  public var tools: [Tool] = []

  /// Optional. List of examples in the app.
  public var examples: [Example] = []

  /// Optional. List of guardrails in the app.
  public var guardrails: [Guardrail] = []

  /// Optional. List of toolsets in the app.
  public var toolsets: [Toolset] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppSnapshot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppSnapshot().with { $0.app = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let app = CodingKeys(stringValue: "app")
    static let agents = CodingKeys(stringValue: "agents")
    static let tools = CodingKeys(stringValue: "tools")
    static let examples = CodingKeys(stringValue: "examples")
    static let guardrails = CodingKeys(stringValue: "guardrails")
    static let toolsets = CodingKeys(stringValue: "toolsets")

    static let _knownKeys: Set<Swift.String> = [
      "app",
      "agents",
      "tools",
      "examples",
      "guardrails",
      "toolsets",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.app = try container.decodeIfPresent(App.self, forKey: .app)
    if let value = try container.decodeIfPresent([Agent].self, forKey: .agents) {
      self.agents = value
    }
    if let value = try container.decodeIfPresent([Tool].self, forKey: .tools) {
      self.tools = value
    }
    if let value = try container.decodeIfPresent([Example].self, forKey: .examples) {
      self.examples = value
    }
    if let value = try container.decodeIfPresent([Guardrail].self, forKey: .guardrails) {
      self.guardrails = value
    }
    if let value = try container.decodeIfPresent([Toolset].self, forKey: .toolsets) {
      self.toolsets = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.app, forKey: .app)
    try container.encode(self.agents, forKey: .agents)
    try container.encode(self.tools, forKey: .tools)
    try container.encode(self.examples, forKey: .examples)
    try container.encode(self.guardrails, forKey: .guardrails)
    try container.encode(self.toolsets, forKey: .toolsets)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.AppSnapshot"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
