// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration for how the input and output audio should be processed and
/// delivered.
public struct AudioProcessingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Configuration of how the agent response should be synthesized,
  /// mapping from the language code to
  /// [SynthesizeSpeechConfig][google.cloud.ces.v1.SynthesizeSpeechConfig].
  ///
  /// If the configuration for the specified language code is not found, the
  /// configuration for the root language code will be used. For example, if the
  /// map contains "en-us" and "en", and the specified language code is "en-gb",
  /// then "en" configuration will be used.
  ///
  /// Note: Language code is case-insensitive.
  ///
  /// [google.cloud.ces.v1.SynthesizeSpeechConfig]: <doc:SynthesizeSpeechConfig>
  public var synthesizeSpeechConfigs: [Swift.String: SynthesizeSpeechConfig] = [:]

  /// Optional. Configures the agent behavior for the user barge-in activities.
  public var bargeInConfig: BargeInConfig? = nil

  /// Optional. The duration of user inactivity (no speech or interaction) before
  /// the agent prompts the user for reengagement. If not set, the agent will not
  /// prompt the user for reengagement.
  public var inactivityTimeout: GoogleCloudWkt.Duration? = nil

  /// Optional. Configuration for the ambient sound to be played with the
  /// synthesized agent response, to enhance the naturalness of the conversation.
  public var ambientSoundConfig: AmbientSoundConfig? = nil

  /// Initialize a new instance of `AudioProcessingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AudioProcessingConfig().with { $0.synthesizeSpeechConfigs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.AudioProcessingConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
