// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for how the user barge-in activities should be handled.
public struct BargeInConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: `disable_barge_in` is deprecated in favor of
  /// [`disable_barge_in_control`][google.cloud.ces.v1.ChannelProfile.disable_barge_in_control]
  /// in ChannelProfile.
  ///
  /// Disables user barge-in while the agent is speaking. If true, user input
  /// during agent response playback will be ignored.
  ///
  /// [google.cloud.ces.v1.ChannelProfile.disable_barge_in_control]: <doc:ChannelProfile/disableBargeInControl>
  @available(*, deprecated)
  public var disableBargeIn: Swift.Bool = Swift.Bool()

  /// Optional. If enabled, the agent will adapt its next response based on the
  /// assumption that the user hasn't heard the full preceding agent message.
  /// This should not be used in scenarios where agent responses are displayed
  /// visually.
  public var bargeInAwareness: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BargeInConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BargeInConfig().with { $0.disableBargeIn = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let disableBargeIn = CodingKeys(stringValue: "disableBargeIn")
    static let bargeInAwareness = CodingKeys(stringValue: "bargeInAwareness")

    static let _knownKeys: Set<Swift.String> = [
      "disableBargeIn",
      "bargeInAwareness",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableBargeIn) {
      self.disableBargeIn = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .bargeInAwareness) {
      self.bargeInAwareness = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.disableBargeIn, forKey: .disableBargeIn)
    try container.encode(self.bargeInAwareness, forKey: .bargeInAwareness)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.BargeInConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
