// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [AgentService.BatchDeleteConversations][google.cloud.ces.v1.AgentService.BatchDeleteConversations].
///
/// [google.cloud.ces.v1.AgentService.BatchDeleteConversations]: <doc:AgentServiceClient/batchDeleteConversations(request:options:)>
public struct BatchDeleteConversationsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The list of conversations that were successfully deleted.
  public var deletedConversations: [Swift.String] = []

  /// The list of conversations that failed to be deleted.
  public var failedConversations: [Swift.String] = []

  /// Optional. A list of error messages associated with conversations that
  /// failed to be deleted.
  public var errorMessages: [Swift.String] = []

  /// Initialize a new instance of `BatchDeleteConversationsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchDeleteConversationsResponse().with { $0.deletedConversations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.BatchDeleteConversationsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
