// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Changelogs represent a change made to the app or to an resource within the
/// app.
public struct Changelog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The unique identifier of the changelog.
  /// Format:
  /// `projects/{project}/locations/{location}/apps/{app}/changelogs/{changelog}`
  public var name: Swift.String = Swift.String()

  /// Output only. Email address of the change author.
  public var author: Swift.String = Swift.String()

  /// Output only. Display name of the change. It typically should be the display
  /// name of the resource that was changed.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Description of the change. which typically captures the
  /// changed fields in the resource.
  public var description: Swift.String = Swift.String()

  /// Output only. The resource that was changed.
  public var resource: Swift.String = Swift.String()

  /// Output only. The type of the resource that was changed.
  public var resourceType: Swift.String = Swift.String()

  /// Output only. The action that was performed on the resource.
  public var action: Swift.String = Swift.String()

  /// Output only. The original resource before the change.
  public var originalResource: GoogleCloudWkt.Struct? = nil

  /// Output only. The new resource after the change.
  public var newResource: GoogleCloudWkt.Struct? = nil

  /// Output only. The dependent resources that were changed.
  public var dependentResources: [GoogleCloudWkt.Struct] = []

  /// Output only. The time when the change was made.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The monotonically increasing sequence number of the changelog.
  public var sequenceNumber: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `Changelog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Changelog().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.Changelog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
