// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A code block to be executed instead of a real tool call.
public struct CodeBlock: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Python code which will be invoked in tool fake mode.
  /// Expected Python function signature -
  /// To catch all tool calls:
  ///   def fake_tool_call(tool: Tool, input: dict[str, Any],
  ///     callback_context: CallbackContext) -> Optional[dict[str, Any]]:
  /// To catch a specific tool call:
  ///   def fake_{tool_id}(tool: Tool, input: dict[str, Any],
  ///     callback_context: CallbackContext) -> Optional[dict[str, Any]]:
  /// If the function returns None, the real tool will be invoked instead.
  public var pythonCode: Swift.String = Swift.String()

  /// Initialize a new instance of `CodeBlock`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CodeBlock().with { $0.pythonCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.CodeBlock"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
