// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A toolset that generates tools from an Integration Connectors Connection.
public struct ConnectorToolset: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The full resource name of the referenced Integration Connectors
  /// Connection.
  /// Format:
  /// `projects/{project}/locations/{location}/connections/{connection}`
  public var connection: Swift.String = Swift.String()

  /// Optional. Configures how authentication is handled in Integration
  /// Connectors. By default, an admin authentication is passed in the
  /// Integration Connectors API requests. You can override it with a different
  /// end-user authentication config.
  /// **Note**: The Connection must have authentication override enabled in
  /// order to specify an EUC configuration here - otherwise, the Toolset
  /// creation will fail. See:
  /// https://cloud.google.com/application-integration/docs/configure-connectors-task#configure-authentication-override
  public var authConfig: EndUserAuthConfig? = nil

  /// Required. The list of connector actions/entity operations to generate tools
  /// for.
  public var connectorActions: [Action] = []

  /// Initialize a new instance of `ConnectorToolset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectorToolset().with { $0.connection = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.ConnectorToolset"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
