// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [AgentService.DeleteTool][google.cloud.ces.v1.AgentService.DeleteTool].
///
/// [google.cloud.ces.v1.AgentService.DeleteTool]: <doc:AgentService/deleteTool(request:)>
public struct DeleteToolRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the tool to delete.
  public var name: Swift.String = Swift.String()

  /// Optional. Indicates whether to forcefully delete the tool, even if it is
  /// still referenced by agents/examples.
  ///
  /// *  If `force = false`, the deletion will fail if any agents still
  /// reference the tool.
  /// *  If `force = true`, all existing references from agents will be removed
  /// and the tool will be deleted.
  public var force: Swift.Bool = Swift.Bool()

  /// Optional. The current etag of the tool. If an etag is not provided, the
  /// deletion will overwrite any concurrent changes. If an etag is provided and
  /// does not match the current etag of the tool, deletion will be blocked and
  /// an ABORTED error will be returned.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `DeleteToolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteToolRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.DeleteToolRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
