// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A deployment represents an immutable, queryable version of the app.
/// It is used to deploy an app version with a specific channel profile.
public struct Deployment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the deployment.
  /// Format:
  /// `projects/{project}/locations/{location}/apps/{app}/deployments/{deployment}`
  public var name: Swift.String = Swift.String()

  /// Required. Display name of the deployment.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The resource name of the app version to deploy.
  /// Format:
  /// `projects/{project}/locations/{location}/apps/{app}/versions/{version}`
  /// Use `projects/{project}/locations/{location}/apps/{app}/versions/-` to use
  /// the draft app.
  public var appVersion: Swift.String = Swift.String()

  /// Required. The channel profile used in the deployment.
  public var channelProfile: ChannelProfile? = nil

  /// Output only. Timestamp when this deployment was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when this deployment was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Etag used to ensure the object hasn't changed during a
  /// read-modify-write operation. If the etag is empty, the update will
  /// overwrite any concurrent changes.
  public var etag: Swift.String = Swift.String()

  /// Optional. Experiment configuration for the deployment.
  public var experimentConfig: ExperimentConfig? = nil

  /// Optional. Input only. Ephemeral WhatsApp credentials required when
  /// configuring a WhatsApp channel profile.
  public var whatsappCredentials: WhatsAppCredentials? = nil

  /// Optional. Input only. Ephemeral Instagram credentials required when
  /// configuring a Instagram channel profile.
  public var instagramCredentials: InstagramCredentials? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let appVersion = CodingKeys(stringValue: "appVersion")
    static let channelProfile = CodingKeys(stringValue: "channelProfile")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let experimentConfig = CodingKeys(stringValue: "experimentConfig")
    static let whatsappCredentials = CodingKeys(stringValue: "whatsappCredentials")
    static let instagramCredentials = CodingKeys(stringValue: "instagramCredentials")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "appVersion",
      "channelProfile",
      "createTime",
      "updateTime",
      "etag",
      "experimentConfig",
      "whatsappCredentials",
      "instagramCredentials",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appVersion) {
      self.appVersion = value
    }
    self.channelProfile = try container.decodeIfPresent(
      ChannelProfile.self, forKey: .channelProfile)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    self.experimentConfig = try container.decodeIfPresent(
      ExperimentConfig.self, forKey: .experimentConfig)
    self.whatsappCredentials = try container.decodeIfPresent(
      WhatsAppCredentials.self, forKey: .whatsappCredentials)
    self.instagramCredentials = try container.decodeIfPresent(
      InstagramCredentials.self, forKey: .instagramCredentials)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.appVersion, forKey: .appVersion)
    try container.encodeIfPresent(self.channelProfile, forKey: .channelProfile)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encodeIfPresent(self.experimentConfig, forKey: .experimentConfig)
    try container.encodeIfPresent(self.whatsappCredentials, forKey: .whatsappCredentials)
    try container.encodeIfPresent(self.instagramCredentials, forKey: .instagramCredentials)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.Deployment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
