// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// End-user authentication configuration used for Connection calls.
/// The field values must be the names of context variables in the format
/// `$context.variables.<name_of_variable>`.
public struct EndUserAuthConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The auth configuration.
  public var authConfig: OneOf_AuthConfig? = nil

  /// Initialize a new instance of `EndUserAuthConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EndUserAuthConfig().with { $0.oauth2AuthCodeConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case oauth2AuthCodeConfig = "oauth2AuthCodeConfig"
    case oauth2JwtBearerConfig = "oauth2JwtBearerConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var authConfig: OneOf_AuthConfig? = nil
    let authConfigCheckAndSet = {
      if authConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authConfig'"))
      }
      authConfig = $0
    }
    if let oauth2AuthCodeConfig = try container.decodeIfPresent(
      EndUserAuthConfig.Oauth2AuthCodeConfig?.self, forKey: .oauth2AuthCodeConfig)
    {
      try authConfigCheckAndSet(.oauth2AuthCodeConfig(oauth2AuthCodeConfig))
    }
    if let oauth2JwtBearerConfig = try container.decodeIfPresent(
      EndUserAuthConfig.Oauth2JwtBearerConfig?.self, forKey: .oauth2JwtBearerConfig)
    {
      try authConfigCheckAndSet(.oauth2JwtBearerConfig(oauth2JwtBearerConfig))
    }
    self.authConfig = authConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.authConfig {
      switch choice {
      case .oauth2AuthCodeConfig(let value):
        try container.encode(value, forKey: .oauth2AuthCodeConfig)
      case .oauth2JwtBearerConfig(let value):
        try container.encode(value, forKey: .oauth2JwtBearerConfig)
      }
    }
  }

  /// Oauth 2.0 Authorization Code authentication configuration.
  public struct Oauth2AuthCodeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Oauth token parameter name to pass through.
    /// Must be in the format `$context.variables.<name_of_variable>`.
    public var oauthToken: Swift.String = Swift.String()

    /// Initialize a new instance of `Oauth2AuthCodeConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2AuthCodeConfig().with { $0.oauthToken = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.EndUserAuthConfig.Oauth2AuthCodeConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// JWT Profile Oauth 2.0 Authorization Grant authentication configuration.
  public struct Oauth2JwtBearerConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Issuer parameter name to pass through.
    /// Must be in the format `$context.variables.<name_of_variable>`.
    public var issuer: Swift.String = Swift.String()

    /// Required. Subject parameter name to pass through.
    /// Must be in the format `$context.variables.<name_of_variable>`.
    public var subject: Swift.String = Swift.String()

    /// Required. Client parameter name to pass through.
    /// Must be in the format `$context.variables.<name_of_variable>`.
    public var clientKey: Swift.String = Swift.String()

    /// Initialize a new instance of `Oauth2JwtBearerConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2JwtBearerConfig().with { $0.issuer = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.EndUserAuthConfig.Oauth2JwtBearerConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The auth configuration.
  public enum OneOf_AuthConfig: Codable, Equatable, Sendable {
    /// Oauth 2.0 Authorization Code authentication.
    indirect case oauth2AuthCodeConfig(EndUserAuthConfig.Oauth2AuthCodeConfig?)
    /// JWT Profile Oauth 2.0 Authorization Grant authentication.
    indirect case oauth2JwtBearerConfig(EndUserAuthConfig.Oauth2JwtBearerConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.EndUserAuthConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
