// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [ToolService.ExecuteTool][google.cloud.ces.v1.ToolService.ExecuteTool].
///
/// [google.cloud.ces.v1.ToolService.ExecuteTool]: <doc:ToolServiceClient/executeTool(request:options:)>
public struct ExecuteToolRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the app which the tool/toolset belongs to.
  /// Format: `projects/{project}/locations/{location}/apps/{app}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The input parameters and values for the tool in JSON object
  /// format.
  public var args: GoogleWKT.Struct? = nil

  /// Optional. Mock configuration for the tool execution.
  /// If this field is set, tools that call other tools will be
  /// mocked based on the provided patterns and responses.
  public var mockConfig: MockConfig? = nil

  /// The identifier of the tool to execute. It could be either a persisted tool
  /// or a tool from a toolset.
  public var toolIdentifier: OneOf_ToolIdentifier? = nil

  /// Additional context to be provided for the tool execution
  public var toolExecutionContext: OneOf_ToolExecutionContext? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExecuteToolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecuteToolRequest().with { $0.tool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tool = CodingKeys(stringValue: "tool")
    static let toolsetTool = CodingKeys(stringValue: "toolsetTool")
    static let variables = CodingKeys(stringValue: "variables")
    static let context = CodingKeys(stringValue: "context")
    static let parent = CodingKeys(stringValue: "parent")
    static let args = CodingKeys(stringValue: "args")
    static let mockConfig = CodingKeys(stringValue: "mockConfig")

    static let _knownKeys: Set<Swift.String> = [
      "tool",
      "toolsetTool",
      "variables",
      "context",
      "parent",
      "args",
      "mockConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.args = try container.decodeIfPresent(GoogleWKT.Struct.self, forKey: .args)
    self.mockConfig = try container.decodeIfPresent(MockConfig.self, forKey: .mockConfig)

    var toolIdentifier: OneOf_ToolIdentifier? = nil
    let toolIdentifierCheckAndSet = {
      if toolIdentifier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolIdentifier'"))
      }
      toolIdentifier = $0
    }
    if let tool = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
      try toolIdentifierCheckAndSet(.tool(tool))
    }
    if let toolsetTool = try container.decodeIfPresent(ToolsetTool?.self, forKey: .toolsetTool) {
      try toolIdentifierCheckAndSet(.toolsetTool(toolsetTool))
    }
    self.toolIdentifier = toolIdentifier

    var toolExecutionContext: OneOf_ToolExecutionContext? = nil
    let toolExecutionContextCheckAndSet = {
      if toolExecutionContext != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolExecutionContext'"))
      }
      toolExecutionContext = $0
    }
    if let variables = try container.decodeIfPresent(GoogleWKT.Struct?.self, forKey: .variables) {
      try toolExecutionContextCheckAndSet(.variables(variables))
    }
    if let context = try container.decodeIfPresent(GoogleWKT.Struct?.self, forKey: .context) {
      try toolExecutionContextCheckAndSet(.context(context))
    }
    self.toolExecutionContext = toolExecutionContext
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.args, forKey: .args)
    try container.encodeIfPresent(self.mockConfig, forKey: .mockConfig)

    if let choice = self.toolIdentifier {
      switch choice {
      case .tool(let value):
        try container.encode(value, forKey: .tool)
      case .toolsetTool(let value):
        try container.encode(value, forKey: .toolsetTool)
      }
    }

    if let choice = self.toolExecutionContext {
      switch choice {
      case .variables(let value):
        try container.encode(value, forKey: .variables)
      case .context(let value):
        try container.encode(value, forKey: .context)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The identifier of the tool to execute. It could be either a persisted tool
  /// or a tool from a toolset.
  public enum OneOf_ToolIdentifier: Codable, Equatable, Sendable {
    /// Optional. The name of the tool to execute.
    /// Format:
    /// projects/{project}/locations/{location}/apps/{app}/tools/{tool}
    case tool(Swift.String)
    /// Optional. The toolset tool to execute. Only one tool should match the
    /// predicate from the toolset. Otherwise, an error will be returned.
    indirect case toolsetTool(ToolsetTool?)
  }

  /// Additional context to be provided for the tool execution
  public enum OneOf_ToolExecutionContext: Codable, Equatable, Sendable {
    /// Optional. The variables that are available for the tool execution.
    indirect case variables(GoogleWKT.Struct?)
    /// Optional. The
    /// [ToolCallContext](https://docs.cloud.google.com/customer-engagement-ai/conversational-agents/ps/tool/python#environment
    /// for details) to be passed to the Python tool.
    indirect case context(GoogleWKT.Struct?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.ExecuteToolRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
