// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [ToolService.ExecuteTool][google.cloud.ces.v1.ToolService.ExecuteTool].
///
/// [google.cloud.ces.v1.ToolService.ExecuteTool]: <doc:ToolServiceClient/executeTool(request:options:)>
public struct ExecuteToolResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The tool execution result in JSON object format.
  /// Use "output" key to specify tool response and "error" key to specify
  /// error details (if any). If "output" and "error" keys are not specified,
  /// then whole "response" is treated as tool execution result.
  public var response: GoogleCloudWKT.Struct? = nil

  /// The variable values at the end of the tool execution.
  public var variables: GoogleCloudWKT.Struct? = nil

  /// Citations that provide the source information for the tool's execution.
  public var citations: Citations? = nil

  /// The suggestions returned from Google Search as a result of invoking the
  /// Google Search Tool during the tool execution.
  public var googleSearchSuggestions: GoogleSearchSuggestions? = nil

  /// The identifier of the tool that got executed.
  public var toolIdentifier: OneOf_ToolIdentifier? = nil

  /// Initialize a new instance of `ExecuteToolResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecuteToolResponse().with { $0.tool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case tool = "tool"
    case toolsetTool = "toolsetTool"
    case response = "response"
    case variables = "variables"
    case citations = "citations"
    case googleSearchSuggestions = "googleSearchSuggestions"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.response = try container.decodeIfPresent(GoogleCloudWKT.Struct.self, forKey: .response)
    self.variables = try container.decodeIfPresent(GoogleCloudWKT.Struct.self, forKey: .variables)
    self.citations = try container.decodeIfPresent(Citations.self, forKey: .citations)
    self.googleSearchSuggestions = try container.decodeIfPresent(
      GoogleSearchSuggestions.self, forKey: .googleSearchSuggestions)

    var toolIdentifier: OneOf_ToolIdentifier? = nil
    let toolIdentifierCheckAndSet = {
      if toolIdentifier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolIdentifier'"))
      }
      toolIdentifier = $0
    }
    if let tool = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
      try toolIdentifierCheckAndSet(.tool(tool))
    }
    if let toolsetTool = try container.decodeIfPresent(ToolsetTool?.self, forKey: .toolsetTool) {
      try toolIdentifierCheckAndSet(.toolsetTool(toolsetTool))
    }
    self.toolIdentifier = toolIdentifier
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.response, forKey: .response)
    try container.encode(self.variables, forKey: .variables)
    try container.encode(self.citations, forKey: .citations)
    try container.encode(self.googleSearchSuggestions, forKey: .googleSearchSuggestions)

    if let choice = self.toolIdentifier {
      switch choice {
      case .tool(let value):
        try container.encode(value, forKey: .tool)
      case .toolsetTool(let value):
        try container.encode(value, forKey: .toolsetTool)
      }
    }
  }

  /// The identifier of the tool that got executed.
  public enum OneOf_ToolIdentifier: Codable, Equatable, Sendable {
    /// The name of the tool that got executed.
    /// Format: `projects/{project}/locations/{location}/apps/{app}/tools/{tool}`
    case tool(Swift.String)
    /// The toolset tool that got executed.
    indirect case toolsetTool(ToolsetTool?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.ExecuteToolResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
