// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response message for
/// [WidgetService.GenerateChatToken][google.cloud.ces.v1.WidgetService.GenerateChatToken].
///
/// [google.cloud.ces.v1.WidgetService.GenerateChatToken]: <doc:WidgetService/generateChatToken(request:)>
public struct GenerateChatTokenResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The session scoped token for chat widget to authenticate with Session APIs.
  public var chatToken: Swift.String = Swift.String()

  /// The time at which the chat token expires.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `GenerateChatTokenResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateChatTokenResponse().with { $0.chatToken = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.GenerateChatTokenResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
