// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [AgentService.ListApps][google.cloud.ces.v1.AgentService.ListApps].
///
/// [google.cloud.ces.v1.AgentService.ListApps]: <doc:AgentService/listApps(request:)>
public struct ListAppsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the location to list apps from.
  public var parent: Swift.String = Swift.String()

  /// Optional. Requested page size. Server may return fewer items than
  /// requested. If unspecified, server will pick an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The
  /// [next_page_token][google.cloud.ces.v1.ListAppsResponse.next_page_token]
  /// value returned from a previous list
  /// [AgentService.ListApps][google.cloud.ces.v1.AgentService.ListApps] call.
  ///
  /// [google.cloud.ces.v1.AgentService.ListApps]: <doc:AgentService/listApps(request:)>
  /// [google.cloud.ces.v1.ListAppsResponse.next_page_token]: <doc:ListAppsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filter to be applied when listing the apps.
  /// See https://google.aip.dev/160 for more details.
  public var filter: Swift.String = Swift.String()

  /// Optional. Field to sort by. Only "name" and "create_time" is supported.
  /// See https://google.aip.dev/132#ordering for more details.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAppsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAppsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.ListAppsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
