// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Settings to describe the logging behaviors for the app.
public struct LoggingSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Configuration for how sensitive data should be redacted.
  public var redactionConfig: RedactionConfig? = nil

  /// Optional. Configuration for how audio interactions should be recorded. The
  /// audio is subject to redaction as configured in
  /// [RedactionConfig][google.cloud.ces.v1.LoggingSettings.redaction_config].
  ///
  /// [google.cloud.ces.v1.LoggingSettings.redaction_config]: <doc:LoggingSettings/redactionConfig>
  public var audioRecordingConfig: AudioRecordingConfig? = nil

  /// Optional. Configures an additional recording of unredacted audio. This can
  /// be used to maintain a raw audio copy when audio redaction is
  /// [enabled][google.cloud.ces.v1.RedactionConfig.enable_redaction], typically
  /// for auditing or monitoring purposes.
  ///
  /// [google.cloud.ces.v1.RedactionConfig.enable_redaction]: <doc:RedactionConfig/enableRedaction>
  public var unredactedAudioRecordingConfig: AudioRecordingConfig? = nil

  /// Optional. Configures the BigQuery export behaviors for the app. The
  /// conversation data is subject to redaction as configured in
  /// [RedactionConfig][google.cloud.ces.v1.LoggingSettings.redaction_config].
  ///
  /// [google.cloud.ces.v1.LoggingSettings.redaction_config]: <doc:LoggingSettings/redactionConfig>
  public var bigqueryExportSettings: BigQueryExportSettings? = nil

  /// Optional. Configures the BigQuery export behaviors for the app.
  /// The unredacted conversation data will be exported to BigQuery tables if it
  /// is enabled.
  public var unredactedBigqueryExportSettings: BigQueryExportSettings? = nil

  /// Optional. Settings to describe the Cloud Logging behaviors for the app.
  public var cloudLoggingSettings: CloudLoggingSettings? = nil

  /// Optional. Settings to describe the conversation logging behaviors for the
  /// app.
  public var conversationLoggingSettings: ConversationLoggingSettings? = nil

  /// Optional. Configuration for how audio interactions should be recorded for
  /// the evaluation. By default, audio recording is not enabled for evaluation
  /// sessions.
  public var evaluationAudioRecordingConfig: AudioRecordingConfig? = nil

  /// Optional. Settings to describe the conversation data collection behaviors
  /// for the LLM analysis pipeline for the app.
  public var metricAnalysisSettings: MetricAnalysisSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoggingSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggingSettings().with { $0.redactionConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let redactionConfig = CodingKeys(stringValue: "redactionConfig")
    static let audioRecordingConfig = CodingKeys(stringValue: "audioRecordingConfig")
    static let unredactedAudioRecordingConfig = CodingKeys(
      stringValue: "unredactedAudioRecordingConfig")
    static let bigqueryExportSettings = CodingKeys(stringValue: "bigqueryExportSettings")
    static let unredactedBigqueryExportSettings = CodingKeys(
      stringValue: "unredactedBigqueryExportSettings")
    static let cloudLoggingSettings = CodingKeys(stringValue: "cloudLoggingSettings")
    static let conversationLoggingSettings = CodingKeys(stringValue: "conversationLoggingSettings")
    static let evaluationAudioRecordingConfig = CodingKeys(
      stringValue: "evaluationAudioRecordingConfig")
    static let metricAnalysisSettings = CodingKeys(stringValue: "metricAnalysisSettings")

    static let _knownKeys: Set<Swift.String> = [
      "redactionConfig",
      "audioRecordingConfig",
      "unredactedAudioRecordingConfig",
      "bigqueryExportSettings",
      "unredactedBigqueryExportSettings",
      "cloudLoggingSettings",
      "conversationLoggingSettings",
      "evaluationAudioRecordingConfig",
      "metricAnalysisSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.redactionConfig = try container.decodeIfPresent(
      RedactionConfig.self, forKey: .redactionConfig)
    self.audioRecordingConfig = try container.decodeIfPresent(
      AudioRecordingConfig.self, forKey: .audioRecordingConfig)
    self.unredactedAudioRecordingConfig = try container.decodeIfPresent(
      AudioRecordingConfig.self, forKey: .unredactedAudioRecordingConfig)
    self.bigqueryExportSettings = try container.decodeIfPresent(
      BigQueryExportSettings.self, forKey: .bigqueryExportSettings)
    self.unredactedBigqueryExportSettings = try container.decodeIfPresent(
      BigQueryExportSettings.self, forKey: .unredactedBigqueryExportSettings)
    self.cloudLoggingSettings = try container.decodeIfPresent(
      CloudLoggingSettings.self, forKey: .cloudLoggingSettings)
    self.conversationLoggingSettings = try container.decodeIfPresent(
      ConversationLoggingSettings.self, forKey: .conversationLoggingSettings)
    self.evaluationAudioRecordingConfig = try container.decodeIfPresent(
      AudioRecordingConfig.self, forKey: .evaluationAudioRecordingConfig)
    self.metricAnalysisSettings = try container.decodeIfPresent(
      MetricAnalysisSettings.self, forKey: .metricAnalysisSettings)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.redactionConfig, forKey: .redactionConfig)
    try container.encodeIfPresent(self.audioRecordingConfig, forKey: .audioRecordingConfig)
    try container.encodeIfPresent(
      self.unredactedAudioRecordingConfig, forKey: .unredactedAudioRecordingConfig)
    try container.encodeIfPresent(self.bigqueryExportSettings, forKey: .bigqueryExportSettings)
    try container.encodeIfPresent(
      self.unredactedBigqueryExportSettings, forKey: .unredactedBigqueryExportSettings)
    try container.encodeIfPresent(self.cloudLoggingSettings, forKey: .cloudLoggingSettings)
    try container.encodeIfPresent(
      self.conversationLoggingSettings, forKey: .conversationLoggingSettings)
    try container.encodeIfPresent(
      self.evaluationAudioRecordingConfig, forKey: .evaluationAudioRecordingConfig)
    try container.encodeIfPresent(self.metricAnalysisSettings, forKey: .metricAnalysisSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.LoggingSettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
