// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Overrides associated with a given tool in a Toolset.
/// This enables "pinning" or "overriding" of tool definitions from the external
/// dynamic server.
public struct McpToolOverride: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The original name of the tool as it is emitted by the MCP server.
  public var tool: Swift.String = Swift.String()

  /// Optional. If present, this tool uses this name in the Agent instead of the
  /// original name. This is primarily used as an alias if the MCP server offers
  /// poorly named tools.
  public var nameOverride: Swift.String = Swift.String()

  /// Optional. If present, this tool uses this description instead of the
  /// original description from the server.
  public var descriptionOverride: Swift.String = Swift.String()

  /// Output only. If present, this tool is "Pinned" and uses the snapshot values
  /// as fallbacks if the server becomes temporarily unavailable or if no
  /// Override is present.
  public var snapshot: McpToolDefinition? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `McpToolOverride`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = McpToolOverride().with { $0.tool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tool = CodingKeys(stringValue: "tool")
    static let nameOverride = CodingKeys(stringValue: "nameOverride")
    static let descriptionOverride = CodingKeys(stringValue: "descriptionOverride")
    static let snapshot = CodingKeys(stringValue: "snapshot")

    static let _knownKeys: Set<Swift.String> = [
      "tool",
      "nameOverride",
      "descriptionOverride",
      "snapshot",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
      self.tool = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nameOverride) {
      self.nameOverride = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .descriptionOverride) {
      self.descriptionOverride = value
    }
    self.snapshot = try container.decodeIfPresent(McpToolDefinition.self, forKey: .snapshot)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.tool, forKey: .tool)
    try container.encode(self.nameOverride, forKey: .nameOverride)
    try container.encode(self.descriptionOverride, forKey: .descriptionOverride)
    try container.encodeIfPresent(self.snapshot, forKey: .snapshot)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.McpToolOverride"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
