// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An MCP tool.
/// See https://modelcontextprotocol.io/specification/2025-06-18/server/tools for
/// more details.
public struct McpTool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the MCP tool.
  public var name: Swift.String = Swift.String()

  /// Optional. The name override of the MCP tool.
  /// This is populated if the name was overridden by a Toolset override.
  public var nameOverride: Swift.String = Swift.String()

  /// Optional. The description of the MCP tool.
  public var description: Swift.String = Swift.String()

  /// Optional. The schema of the input arguments of the MCP tool.
  public var inputSchema: Schema? = nil

  /// Optional. The schema of the output arguments of the MCP tool.
  public var outputSchema: Schema? = nil

  /// Required. The server address of the MCP server, e.g.,
  /// "https://example.com/mcp/". If the server is built with the MCP SDK, the
  /// url should be suffixed with
  /// "/mcp/". Only Streamable HTTP transport based servers are supported. This
  /// is the same as the server_address in the McpToolset. See
  /// https://modelcontextprotocol.io/specification/2025-03-26/basic/transports#streamable-http
  /// for more details.
  public var serverAddress: Swift.String = Swift.String()

  /// Optional. Authentication information required to execute the tool against
  /// the MCP server. For bearer token authentication, the token applies only to
  /// tool execution, not to listing tools. This requires that tools can be
  /// listed without authentication.
  public var apiAuthentication: ApiAuthentication? = nil

  /// Optional. The TLS configuration. Includes the custom server certificates
  /// that the client should trust.
  public var tlsConfig: TlsConfig? = nil

  /// Optional. Service Directory configuration for VPC-SC, used to resolve
  /// service names within a perimeter.
  public var serviceDirectoryConfig: ServiceDirectoryConfig? = nil

  /// Optional. The custom headers to send in the request to the MCP server. The
  /// values must be in the format `$context.variables.<name_of_variable>` and
  /// can be set in the session variables. See
  /// https://docs.cloud.google.com/customer-engagement-ai/conversational-agents/ps/tool/open-api#openapi-injection
  /// for more details.
  public var customHeaders: [Swift.String: Swift.String] = [:]

  /// Output only. The dynamic availability state of the tool on the external
  /// server.
  public var state: McpTool.State = McpTool.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `McpTool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = McpTool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let nameOverride = CodingKeys(stringValue: "nameOverride")
    static let description = CodingKeys(stringValue: "description")
    static let inputSchema = CodingKeys(stringValue: "inputSchema")
    static let outputSchema = CodingKeys(stringValue: "outputSchema")
    static let serverAddress = CodingKeys(stringValue: "serverAddress")
    static let apiAuthentication = CodingKeys(stringValue: "apiAuthentication")
    static let tlsConfig = CodingKeys(stringValue: "tlsConfig")
    static let serviceDirectoryConfig = CodingKeys(stringValue: "serviceDirectoryConfig")
    static let customHeaders = CodingKeys(stringValue: "customHeaders")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "nameOverride",
      "description",
      "inputSchema",
      "outputSchema",
      "serverAddress",
      "apiAuthentication",
      "tlsConfig",
      "serviceDirectoryConfig",
      "customHeaders",
      "state",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nameOverride) {
      self.nameOverride = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.inputSchema = try container.decodeIfPresent(Schema.self, forKey: .inputSchema)
    self.outputSchema = try container.decodeIfPresent(Schema.self, forKey: .outputSchema)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serverAddress) {
      self.serverAddress = value
    }
    self.apiAuthentication = try container.decodeIfPresent(
      ApiAuthentication.self, forKey: .apiAuthentication)
    self.tlsConfig = try container.decodeIfPresent(TlsConfig.self, forKey: .tlsConfig)
    self.serviceDirectoryConfig = try container.decodeIfPresent(
      ServiceDirectoryConfig.self, forKey: .serviceDirectoryConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .customHeaders)
    {
      self.customHeaders = value
    }
    if let value = try container.decodeIfPresent(McpTool.State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.nameOverride, forKey: .nameOverride)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.inputSchema, forKey: .inputSchema)
    try container.encodeIfPresent(self.outputSchema, forKey: .outputSchema)
    try container.encode(self.serverAddress, forKey: .serverAddress)
    try container.encodeIfPresent(self.apiAuthentication, forKey: .apiAuthentication)
    try container.encodeIfPresent(self.tlsConfig, forKey: .tlsConfig)
    try container.encodeIfPresent(self.serviceDirectoryConfig, forKey: .serviceDirectoryConfig)
    try container.encode(self.customHeaders, forKey: .customHeaders)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the dynamic availability state of the tool.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Default state.
    case unspecified
    /// The tool is available and actively offered by the server.
    case active
    /// The tool is configured or pinned, but currently not offered by the
    /// server.
    case inactive
    /// The tool exists on the server, but does not match the version on the
    /// server.
    case stale
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .stale: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .inactive: return "INACTIVE"
      case .stale: return "STALE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "INACTIVE": self = .inactive
      case "STALE": self = .stale
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      case 3: self = .stale
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .inactive: return try container.encode("INACTIVE")
      case .stale: return try container.encode("STALE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.McpTool"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
