// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A mocked tool call.
///
/// Expresses the target tool + a pattern to match against that tool's
/// args / inputs. If the pattern matches, then the mock response will be
/// returned.
public struct MockedToolCall: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Deprecated. Use tool_identifier instead.
  @available(*, deprecated)
  public var tool: Swift.String = Swift.String()

  /// Required. A pattern to match against the args / inputs of all dispatched
  /// tool calls. If the tool call inputs match this pattern, then mock output
  /// will be returned.
  public var expectedArgsPattern: GoogleWKT.WKTStruct? = nil

  /// Optional. The mock response / output to return if the tool call args /
  /// inputs match the pattern.
  public var mockResponse: GoogleWKT.WKTStruct? = nil

  /// The identifier of the tool to mock.
  public var toolIdentifier: OneOf_ToolIdentifier? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MockedToolCall`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MockedToolCall().with { $0.toolId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let toolId = CodingKeys(stringValue: "toolId")
    static let toolset = CodingKeys(stringValue: "toolset")
    static let tool = CodingKeys(stringValue: "tool")
    static let expectedArgsPattern = CodingKeys(stringValue: "expectedArgsPattern")
    static let mockResponse = CodingKeys(stringValue: "mockResponse")

    static let _knownKeys: Set<Swift.String> = [
      "toolId",
      "toolset",
      "tool",
      "expectedArgsPattern",
      "mockResponse",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
      self.tool = value
    }
    self.expectedArgsPattern = try container.decodeIfPresent(
      GoogleWKT.WKTStruct.self, forKey: .expectedArgsPattern)
    self.mockResponse = try container.decodeIfPresent(
      GoogleWKT.WKTStruct.self, forKey: .mockResponse)

    var toolIdentifier: OneOf_ToolIdentifier? = nil
    let toolIdentifierCheckAndSet = {
      if toolIdentifier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolIdentifier'"))
      }
      toolIdentifier = $0
    }
    if let toolId = try container.decodeIfPresent(Swift.String.self, forKey: .toolId) {
      try toolIdentifierCheckAndSet(.toolId(toolId))
    }
    if let toolset = try container.decodeIfPresent(ToolsetTool?.self, forKey: .toolset) {
      try toolIdentifierCheckAndSet(.toolset(toolset))
    }
    self.toolIdentifier = toolIdentifier
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.tool, forKey: .tool)
    try container.encodeIfPresent(self.expectedArgsPattern, forKey: .expectedArgsPattern)
    try container.encodeIfPresent(self.mockResponse, forKey: .mockResponse)

    if let choice = self.toolIdentifier {
      switch choice {
      case .toolId(let value):
        try container.encode(value, forKey: .toolId)
      case .toolset(let value):
        try container.encode(value, forKey: .toolset)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The identifier of the tool to mock.
  public enum OneOf_ToolIdentifier: Codable, Equatable, Sendable {
    /// Optional. The name of the tool to mock.
    /// Format: `projects/{project}/locations/{location}/apps/{app}/tools/{tool}`
    case toolId(Swift.String)
    /// Optional. The toolset to mock.
    indirect case toolset(ToolsetTool?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.MockedToolCall"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
