// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// OmnichannelIntegrationConfig contains all App integration configs.
public struct OmnichannelIntegrationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Various of configuration for handling App events.
  public var channelConfigs: [Swift.String: OmnichannelIntegrationConfig.ChannelConfig] = [:]

  /// Optional. Various of subscribers configs.
  public var subscriberConfigs: [Swift.String: OmnichannelIntegrationConfig.SubscriberConfig] = [:]

  /// Optional. The key of routing_configs is a key of `app_configs`, value is a
  /// `RoutingConfig`, which contains subscriber's key.
  public var routingConfigs: [Swift.String: OmnichannelIntegrationConfig.RoutingConfig] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `OmnichannelIntegrationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OmnichannelIntegrationConfig().with { $0.channelConfigs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let channelConfigs = CodingKeys(stringValue: "channelConfigs")
    static let subscriberConfigs = CodingKeys(stringValue: "subscriberConfigs")
    static let routingConfigs = CodingKeys(stringValue: "routingConfigs")

    static let _knownKeys: Set<Swift.String> = [
      "channelConfigs",
      "subscriberConfigs",
      "routingConfigs",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: OmnichannelIntegrationConfig.ChannelConfig].self, forKey: .channelConfigs)
    {
      self.channelConfigs = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: OmnichannelIntegrationConfig.SubscriberConfig].self, forKey: .subscriberConfigs
    ) {
      self.subscriberConfigs = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: OmnichannelIntegrationConfig.RoutingConfig].self, forKey: .routingConfigs)
    {
      self.routingConfigs = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.channelConfigs, forKey: .channelConfigs)
    try container.encode(self.subscriberConfigs, forKey: .subscriberConfigs)
    try container.encode(self.routingConfigs, forKey: .routingConfigs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// ChannelConfig contains config for various of app integration.
  public struct ChannelConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The config for the app.
    public var channelConfig: OneOf_ChannelConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ChannelConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ChannelConfig().with { $0.whatsappConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let whatsappConfig = CodingKeys(stringValue: "whatsappConfig")

      static let _knownKeys: Set<Swift.String> = [
        "whatsappConfig"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var channelConfig: OneOf_ChannelConfig? = nil
      let channelConfigCheckAndSet = {
        if channelConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'channelConfig'"))
        }
        channelConfig = $0
      }
      if let whatsappConfig = try container.decodeIfPresent(
        OmnichannelIntegrationConfig.WhatsappConfig?.self, forKey: .whatsappConfig)
      {
        try channelConfigCheckAndSet(.whatsappConfig(whatsappConfig))
      }
      self.channelConfig = channelConfig
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.channelConfig {
        switch choice {
        case .whatsappConfig(let value):
          try container.encode(value, forKey: .whatsappConfig)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The config for the app.
    public enum OneOf_ChannelConfig: Codable, Equatable, Sendable {
      /// WhatsApp config.
      indirect case whatsappConfig(OmnichannelIntegrationConfig.WhatsappConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.OmnichannelIntegrationConfig.ChannelConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// How Omnichannel should receive/reply events from WhatsApp.
  public struct WhatsappConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The Phone Number ID associated with the WhatsApp Business Account.
    public var phoneNumberId: Swift.String = Swift.String()

    /// The phone number used for sending/receiving messages.
    public var phoneNumber: Swift.String = Swift.String()

    /// The customer's WhatsApp Business Account (WABA) ID.
    public var whatsappBusinessAccountId: Swift.String = Swift.String()

    /// The verify token configured in the Meta App Dashboard for webhook
    /// verification.
    public var webhookVerifyToken: Swift.String = Swift.String()

    /// The access token for authenticating API calls to the WhatsApp Cloud API.
    /// https://developers.facebook.com/docs/whatsapp/business-management-api/get-started/#business-integration-system-user-access-tokens
    public var whatsappBusinessToken: Swift.String = Swift.String()

    /// The Meta Business Portfolio (MBP) ID.
    /// https://www.facebook.com/business/help/1710077379203657
    public var metaBusinessPortfolioId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `WhatsappConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WhatsappConfig().with { $0.phoneNumberId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let phoneNumberId = CodingKeys(stringValue: "phoneNumberId")
      static let phoneNumber = CodingKeys(stringValue: "phoneNumber")
      static let whatsappBusinessAccountId = CodingKeys(stringValue: "whatsappBusinessAccountId")
      static let webhookVerifyToken = CodingKeys(stringValue: "webhookVerifyToken")
      static let whatsappBusinessToken = CodingKeys(stringValue: "whatsappBusinessToken")
      static let metaBusinessPortfolioId = CodingKeys(stringValue: "metaBusinessPortfolioId")

      static let _knownKeys: Set<Swift.String> = [
        "phoneNumberId",
        "phoneNumber",
        "whatsappBusinessAccountId",
        "webhookVerifyToken",
        "whatsappBusinessToken",
        "metaBusinessPortfolioId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .phoneNumberId) {
        self.phoneNumberId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .phoneNumber) {
        self.phoneNumber = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .whatsappBusinessAccountId)
      {
        self.whatsappBusinessAccountId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .webhookVerifyToken) {
        self.webhookVerifyToken = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .whatsappBusinessToken)
      {
        self.whatsappBusinessToken = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .metaBusinessPortfolioId)
      {
        self.metaBusinessPortfolioId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.phoneNumberId, forKey: .phoneNumberId)
      try container.encode(self.phoneNumber, forKey: .phoneNumber)
      try container.encode(self.whatsappBusinessAccountId, forKey: .whatsappBusinessAccountId)
      try container.encode(self.webhookVerifyToken, forKey: .webhookVerifyToken)
      try container.encode(self.whatsappBusinessToken, forKey: .whatsappBusinessToken)
      try container.encode(self.metaBusinessPortfolioId, forKey: .metaBusinessPortfolioId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.OmnichannelIntegrationConfig.WhatsappConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configs of subscribers.
  public struct SubscriberConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The config for the subscriber.
    public var subscriberConfig: OneOf_SubscriberConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SubscriberConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubscriberConfig().with { $0.cesAppConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cesAppConfig = CodingKeys(stringValue: "cesAppConfig")

      static let _knownKeys: Set<Swift.String> = [
        "cesAppConfig"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var subscriberConfig: OneOf_SubscriberConfig? = nil
      let subscriberConfigCheckAndSet = {
        if subscriberConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'subscriberConfig'"))
        }
        subscriberConfig = $0
      }
      if let cesAppConfig = try container.decodeIfPresent(
        OmnichannelIntegrationConfig.CesAppConfig?.self, forKey: .cesAppConfig)
      {
        try subscriberConfigCheckAndSet(.cesAppConfig(cesAppConfig))
      }
      self.subscriberConfig = subscriberConfig
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.subscriberConfig {
        switch choice {
        case .cesAppConfig(let value):
          try container.encode(value, forKey: .cesAppConfig)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The config for the subscriber.
    public enum OneOf_SubscriberConfig: Codable, Equatable, Sendable {
      /// Ces app config.
      indirect case cesAppConfig(OmnichannelIntegrationConfig.CesAppConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.OmnichannelIntegrationConfig.SubscriberConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configs for CES app.
  public struct CesAppConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The unique identifier of the CES app.
    /// Format: `projects/{project}/locations/{location}/apps/{app}`
    public var app: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `CesAppConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CesAppConfig().with { $0.app = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let app = CodingKeys(stringValue: "app")

      static let _knownKeys: Set<Swift.String> = [
        "app"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .app) {
        self.app = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.app, forKey: .app)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.OmnichannelIntegrationConfig.CesAppConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Routing config specify how/who to route app events to a subscriber.
  public struct RoutingConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The key of the subscriber.
    public var subscriberKey: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `RoutingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RoutingConfig().with { $0.subscriberKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let subscriberKey = CodingKeys(stringValue: "subscriberKey")

      static let _knownKeys: Set<Swift.String> = [
        "subscriberKey"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subscriberKey) {
        self.subscriberKey = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.subscriberKey, forKey: .subscriberKey)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.OmnichannelIntegrationConfig.RoutingConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.OmnichannelIntegrationConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
