// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A remote API tool defined by an OpenAPI schema.
public struct OpenApiTool: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The OpenAPI schema in JSON or YAML format.
  public var openApiSchema: Swift.String = Swift.String()

  /// Optional. The name of the tool. If not provided, the name of the tool will
  /// be derived from the OpenAPI schema, from `operation.operationId`.
  public var name: Swift.String = Swift.String()

  /// Optional. The description of the tool. If not provided, the description of
  /// the tool will be derived from the OpenAPI schema, from
  /// `operation.description` or `operation.summary`.
  public var description: Swift.String = Swift.String()

  /// Optional. Authentication information required by the API.
  public var apiAuthentication: ApiAuthentication? = nil

  /// Optional. The TLS configuration. Includes the custom server certificates
  /// that the client will trust.
  public var tlsConfig: TlsConfig? = nil

  /// Optional. Service Directory configuration.
  public var serviceDirectoryConfig: ServiceDirectoryConfig? = nil

  /// Optional. If true, the agent will ignore unknown fields in the API
  /// response.
  public var ignoreUnknownFields: Swift.Bool = Swift.Bool()

  /// Optional. The server URL of the Open API schema.
  /// This field is only set in tools in the environment dependencies during the
  /// export process if the schema contains a server url. During the import
  /// process, if this url is present in the environment dependencies and the
  /// schema has the $env_var placeholder, it will replace the placeholder in the
  /// schema.
  public var url: Swift.String = Swift.String()

  /// Initialize a new instance of `OpenApiTool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OpenApiTool().with { $0.openApiSchema = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.OpenApiTool"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
