// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration to instruct how sensitive data should be handled.
public struct RedactionConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. If true, redaction will be applied in various logging scenarios,
  /// including conversation history, Cloud Logging and audio recording.
  public var enableRedaction: Swift.Bool = Swift.Bool()

  /// Optional. [DLP](https://cloud.google.com/dlp/docs) inspect template name to
  /// configure detection of sensitive data types.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/inspectTemplates/{inspect_template}`
  public var inspectTemplate: Swift.String = Swift.String()

  /// Optional. [DLP](https://cloud.google.com/dlp/docs) deidentify template name
  /// to instruct on how to de-identify content.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/deidentifyTemplates/{deidentify_template}`
  public var deidentifyTemplate: Swift.String = Swift.String()

  /// Initialize a new instance of `RedactionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RedactionConfig().with { $0.enableRedaction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.RedactionConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
