// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [ToolService.RetrieveToolSchema][google.cloud.ces.v1.ToolService.RetrieveToolSchema].
///
/// [google.cloud.ces.v1.ToolService.RetrieveToolSchema]: <doc:ToolServiceClient/retrieveToolSchema(request:options:)>
public struct RetrieveToolSchemaRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the app which the tool/toolset belongs to.
  /// Format: `projects/{project}/locations/{location}/apps/{app}`
  public var parent: Swift.String = Swift.String()

  /// The identifier of the tool to retrieve the schema for. It could be either a
  /// persisted tool or a tool from a toolset.
  public var toolIdentifier: OneOf_ToolIdentifier? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RetrieveToolSchemaRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RetrieveToolSchemaRequest().with { $0.tool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tool = CodingKeys(stringValue: "tool")
    static let toolsetTool = CodingKeys(stringValue: "toolsetTool")
    static let parent = CodingKeys(stringValue: "parent")

    static let _knownKeys: Set<Swift.String> = [
      "tool",
      "toolsetTool",
      "parent",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }

    var toolIdentifier: OneOf_ToolIdentifier? = nil
    let toolIdentifierCheckAndSet = {
      if toolIdentifier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolIdentifier'"))
      }
      toolIdentifier = $0
    }
    if let tool = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
      try toolIdentifierCheckAndSet(.tool(tool))
    }
    if let toolsetTool = try container.decodeIfPresent(ToolsetTool?.self, forKey: .toolsetTool) {
      try toolIdentifierCheckAndSet(.toolsetTool(toolsetTool))
    }
    self.toolIdentifier = toolIdentifier
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)

    if let choice = self.toolIdentifier {
      switch choice {
      case .tool(let value):
        try container.encode(value, forKey: .tool)
      case .toolsetTool(let value):
        try container.encode(value, forKey: .toolsetTool)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The identifier of the tool to retrieve the schema for. It could be either a
  /// persisted tool or a tool from a toolset.
  public enum OneOf_ToolIdentifier: Codable, Equatable, Sendable {
    /// Optional. The name of the tool to retrieve the schema for.
    /// Format:
    /// projects/{project}/locations/{location}/apps/{app}/tools/{tool}
    case tool(Swift.String)
    /// Optional. The toolset tool to retrieve the schema for. Only one tool
    /// should match the predicate from the toolset. Otherwise, an error will be
    /// returned.
    indirect case toolsetTool(ToolsetTool?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.RetrieveToolSchemaRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
