// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents a select subset of an OpenAPI 3.0 schema object.
public struct Schema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The type of the data.
  public var type: Schema.Type_ = Schema.Type_()

  /// Optional. Properties of Type.OBJECT.
  public var properties: [Swift.String: Schema] = [:]

  /// Optional. Required properties of Type.OBJECT.
  public var `required`: [Swift.String] = []

  /// Optional. The description of the data.
  public var description: Swift.String = Swift.String()

  /// Optional. Schema of the elements of Type.ARRAY.
  public var items: GoogleCloudWkt.Recursive<Schema>? = nil

  /// Optional. Indicates if the value may be null.
  public var nullable: Swift.Bool = Swift.Bool()

  /// Optional. Indicate the items in the array must be unique. Only applies to
  /// TYPE.ARRAY.
  public var uniqueItems: Swift.Bool = Swift.Bool()

  /// Optional. Schemas of initial elements of Type.ARRAY.
  public var prefixItems: [Schema] = []

  /// Optional. Can either be a boolean or an object, controls the presence of
  /// additional properties.
  public var additionalProperties: GoogleCloudWkt.Recursive<Schema>? = nil

  /// Optional. The value should be validated against any (one or more) of the
  /// subschemas in the list.
  public var anyOf: [Schema] = []

  /// Optional. Possible values of the element of primitive type with enum
  /// format. Examples:
  /// 1. We can define direction as :
  /// {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH", "WEST"]}
  /// 2. We can define apartment number as :
  /// {type:INTEGER, format:enum, enum:["101", "201", "301"]}
  public var `enum`: [Swift.String] = []

  /// Optional. Default value of the data.
  public var `default`: GoogleCloudWkt.Value? = nil

  /// Optional. Allows indirect references between schema nodes. The value should
  /// be a valid reference to a child of the root `defs`.
  ///
  /// For example, the following schema defines a reference to a schema node
  /// named "Pet":
  ///
  /// ```
  /// type: object
  /// properties:
  ///   pet:
  ///     ref: #/defs/Pet
  /// defs:
  ///   Pet:
  ///     type: object
  ///     properties:
  ///       name:
  ///         type: string
  /// ```
  ///
  /// The value of the "pet" property is a reference to the schema node
  /// named "Pet".
  /// See details in
  /// https://json-schema.org/understanding-json-schema/structuring.
  public var ref: Swift.String = Swift.String()

  /// Optional. A map of definitions for use by `ref`. Only allowed at the root
  /// of the schema.
  public var defs: [Swift.String: Schema] = [:]

  /// Optional. The title of the schema.
  public var title: Swift.String = Swift.String()

  /// Optional. Minimum number of the elements for Type.ARRAY.
  public var minItems: Swift.Int64 = Swift.Int64()

  /// Optional. Maximum number of the elements for Type.ARRAY.
  public var maxItems: Swift.Int64 = Swift.Int64()

  /// Optional. Minimum value for Type.INTEGER and Type.NUMBER.
  public var minimum: Swift.Double? = nil

  /// Optional. Maximum value for Type.INTEGER and Type.NUMBER.
  public var maximum: Swift.Double? = nil

  /// Initialize a new instance of `Schema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Schema().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case type = "type"
    case properties = "properties"
    case `required` = "required"
    case description = "description"
    case items = "items"
    case nullable = "nullable"
    case uniqueItems = "uniqueItems"
    case prefixItems = "prefixItems"
    case additionalProperties = "additionalProperties"
    case anyOf = "anyOf"
    case `enum` = "enum"
    case `default` = "default"
    case ref = "ref"
    case defs = "defs"
    case title = "title"
    case minItems = "minItems"
    case maxItems = "maxItems"
    case minimum = "minimum"
    case maximum = "maximum"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.type = try container.decode(Schema.Type_.self, forKey: .type)
    self.properties = try container.decode([Swift.String: Schema].self, forKey: .properties)
    self.`required` = try container.decode([Swift.String].self, forKey: .`required`)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.items = try container.decodeIfPresent(
      GoogleCloudWkt.Recursive<Schema>.self, forKey: .items)
    self.nullable = try container.decode(Swift.Bool.self, forKey: .nullable)
    self.uniqueItems = try container.decode(Swift.Bool.self, forKey: .uniqueItems)
    self.prefixItems = try container.decode([Schema].self, forKey: .prefixItems)
    self.additionalProperties = try container.decodeIfPresent(
      GoogleCloudWkt.Recursive<Schema>.self, forKey: .additionalProperties)
    self.anyOf = try container.decode([Schema].self, forKey: .anyOf)
    self.`enum` = try container.decode([Swift.String].self, forKey: .`enum`)
    self.`default` = try container.decodeIfPresent(GoogleCloudWkt.Value.self, forKey: .`default`)
    self.ref = try container.decode(Swift.String.self, forKey: .ref)
    self.defs = try container.decode([Swift.String: Schema].self, forKey: .defs)
    self.title = try container.decode(Swift.String.self, forKey: .title)
    self.minItems = try container.decode(Swift.Int64.self, forKey: .minItems)
    self.maxItems = try container.decode(Swift.Int64.self, forKey: .maxItems)
    self.minimum = try container.decodeIfPresent(Swift.Double.self, forKey: .minimum)
    self.maximum = try container.decodeIfPresent(Swift.Double.self, forKey: .maximum)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.properties, forKey: .properties)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.items, forKey: .items)
    try container.encode(self.nullable, forKey: .nullable)
    try container.encode(self.uniqueItems, forKey: .uniqueItems)
    try container.encode(self.prefixItems, forKey: .prefixItems)
    try container.encode(self.additionalProperties, forKey: .additionalProperties)
    try container.encode(self.anyOf, forKey: .anyOf)
    try container.encode(self.`enum`, forKey: .`enum`)
    try container.encode(self.`default`, forKey: .`default`)
    try container.encode(self.ref, forKey: .ref)
    try container.encode(self.defs, forKey: .defs)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.minItems, forKey: .minItems)
    try container.encode(self.maxItems, forKey: .maxItems)
    try container.encode(self.minimum, forKey: .minimum)
    try container.encode(self.maximum, forKey: .maximum)
  }

  /// OpenAPI data types.
  public enum Type_: Codable, Equatable, Sendable {
    /// Type unspecified.
    case unspecified
    /// String type.
    case string
    /// Integer type.
    case integer
    /// Number type.
    case number
    /// Boolean type.
    case boolean
    /// Object type.
    case object
    /// Array type.
    case array
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .integer: return 2
      case .number: return 3
      case .boolean: return 4
      case .object: return 5
      case .array: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .integer: return "INTEGER"
      case .number: return "NUMBER"
      case .boolean: return "BOOLEAN"
      case .object: return "OBJECT"
      case .array: return "ARRAY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INTEGER": self = .integer
      case "NUMBER": self = .number
      case "BOOLEAN": self = .boolean
      case "OBJECT": self = .object
      case "ARRAY": self = .array
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .integer
      case 3: self = .number
      case 4: self = .boolean
      case 5: self = .object
      case 6: self = .array
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .string: return try container.encode(1)
      case .integer: return try container.encode(2)
      case .number: return try container.encode(3)
      case .boolean: return try container.encode(4)
      case .object: return try container.encode(5)
      case .array: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.Schema"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
