// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration for how the agent response should be synthesized.
public struct SynthesizeSpeechConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The name of the voice. If not set, the service will choose a
  /// voice based on the other parameters such as language_code.
  ///
  /// For the list of available voices, please refer to [Supported voices and
  /// languages](https://cloud.google.com/text-to-speech/docs/voices) from Cloud
  /// Text-to-Speech.
  public var voice: Swift.String = Swift.String()

  /// Optional. The Cloud Storage URI to the audio sample for voice cloning. The
  /// audio sample should be a mono-channel, 24kHz WAV file.
  ///
  /// Note: Please make sure the CES service agent
  /// `service-<PROJECT-NUMBER>@gcp-sa-ces.iam.gserviceaccount.com` has
  /// `storage.objects.get` permission to the Cloud Storage object.
  public var voiceSampleGcsUri: Swift.String = Swift.String()

  /// Optional. The speaking rate/speed in the range [0.25, 2.0]. 1.0 is the
  /// normal native speed supported by the specific voice. 2.0 is twice as fast,
  /// and 0.5 is half as fast. Values outside of the range [0.25, 2.0] will
  /// return an error.
  public var speakingRate: Swift.Double = Swift.Double()

  /// Optional. The model used to synthesize audio.
  /// Currently supported values:
  /// - "gemini-3.1-flash-tts-preview"
  /// If empty, Chirp3-HD is used.
  public var model: Swift.String = Swift.String()

  /// Optional. The instruction used to synthesize speech when using a generative
  /// model.
  public var instruction: Swift.String = Swift.String()

  /// Initialize a new instance of `SynthesizeSpeechConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SynthesizeSpeechConfig().with { $0.voice = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.SynthesizeSpeechConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
