// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The execution result of a specific tool from the client or the agent.
public struct ToolResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The matching ID of the [tool call][google.cloud.ces.v1.ToolCall]
  /// the response is for.
  ///
  /// [google.cloud.ces.v1.ToolCall]: <doc:ToolCall>
  public var id: Swift.String = Swift.String()

  /// Output only. Display name of the tool.
  public var displayName: Swift.String = Swift.String()

  /// Required. The tool execution result in JSON object format.
  /// Use "output" key to specify tool response and "error" key to specify
  /// error details (if any). If "output" and "error" keys are not specified,
  /// then whole "response" is treated as tool execution result.
  public var response: GoogleCloudWkt.Struct? = nil

  /// The identifier of the tool that got executed. It could be either a
  /// persisted tool or a tool from a toolset.
  public var toolIdentifier: OneOf_ToolIdentifier? = nil

  /// Initialize a new instance of `ToolResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ToolResponse().with { $0.tool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case tool = "tool"
    case toolsetTool = "toolsetTool"
    case id = "id"
    case displayName = "displayName"
    case response = "response"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.response = try container.decodeIfPresent(GoogleCloudWkt.Struct.self, forKey: .response)

    var toolIdentifier: OneOf_ToolIdentifier? = nil
    let toolIdentifierCheckAndSet = {
      if toolIdentifier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolIdentifier'"))
      }
      toolIdentifier = $0
    }
    if let tool = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
      try toolIdentifierCheckAndSet(.tool(tool))
    }
    if let toolsetTool = try container.decodeIfPresent(ToolsetTool?.self, forKey: .toolsetTool) {
      try toolIdentifierCheckAndSet(.toolsetTool(toolsetTool))
    }
    self.toolIdentifier = toolIdentifier
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.response, forKey: .response)

    if let choice = self.toolIdentifier {
      switch choice {
      case .tool(let value):
        try container.encode(value, forKey: .tool)
      case .toolsetTool(let value):
        try container.encode(value, forKey: .toolsetTool)
      }
    }
  }

  /// The identifier of the tool that got executed. It could be either a
  /// persisted tool or a tool from a toolset.
  public enum OneOf_ToolIdentifier: Codable, Equatable, Sendable {
    /// Optional. The name of the tool to execute.
    /// Format: `projects/{project}/locations/{location}/apps/{app}/tools/{tool}`
    case tool(Swift.String)
    /// Optional. The toolset tool that got executed.
    indirect case toolsetTool(ToolsetTool?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.ToolResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
