// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A toolset represents a group of dynamically managed tools that can be used
/// by the agent.
public struct Toolset: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The unique identifier of the toolset.
  /// Format:
  /// `projects/{project}/locations/{location}/apps/{app}/toolsets/{toolset}`
  public var name: Swift.String = Swift.String()

  /// Optional. The display name of the toolset. Must be unique within the same
  /// app.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the toolset.
  public var description: Swift.String = Swift.String()

  /// Optional. The timeout for the toolset execution. If not set, the default
  /// timeout is 30 seconds for `SYNCHRONOUS` toolsets and 60 seconds for
  /// `ASYNCHRONOUS` toolsets.
  public var timeout: GoogleWKT.WKTDuration? = nil

  /// Output only. Timestamp when the toolset was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when the toolset was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// ETag used to ensure the object hasn't changed during a read-modify-write
  /// operation. If the etag is empty, the update will overwrite any concurrent
  /// changes.
  public var etag: Swift.String = Swift.String()

  /// Optional. The execution type of the tools in the toolset.
  public var executionType: ExecutionType = ExecutionType()

  /// Optional. Configuration for tools behavior in fake mode.
  public var toolFakeConfig: ToolFakeConfig? = nil

  /// The type of the toolset.
  public var toolsetType: OneOf_ToolsetType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Toolset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Toolset().with { $0.mcpToolset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mcpToolset = CodingKeys(stringValue: "mcpToolset")
    static let openApiToolset = CodingKeys(stringValue: "openApiToolset")
    static let connectorToolset = CodingKeys(stringValue: "connectorToolset")
    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let timeout = CodingKeys(stringValue: "timeout")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let executionType = CodingKeys(stringValue: "executionType")
    static let toolFakeConfig = CodingKeys(stringValue: "toolFakeConfig")

    static let _knownKeys: Set<Swift.String> = [
      "mcpToolset",
      "openApiToolset",
      "connectorToolset",
      "name",
      "displayName",
      "description",
      "timeout",
      "createTime",
      "updateTime",
      "etag",
      "executionType",
      "toolFakeConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.timeout = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .timeout)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(ExecutionType.self, forKey: .executionType) {
      self.executionType = value
    }
    self.toolFakeConfig = try container.decodeIfPresent(
      ToolFakeConfig.self, forKey: .toolFakeConfig)

    var toolsetType: OneOf_ToolsetType? = nil
    let toolsetTypeCheckAndSet = {
      if toolsetType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolsetType'"))
      }
      toolsetType = $0
    }
    if let mcpToolset = try container.decodeIfPresent(McpToolset?.self, forKey: .mcpToolset) {
      try toolsetTypeCheckAndSet(.mcpToolset(mcpToolset))
    }
    if let openApiToolset = try container.decodeIfPresent(
      OpenApiToolset?.self, forKey: .openApiToolset)
    {
      try toolsetTypeCheckAndSet(.openApiToolset(openApiToolset))
    }
    if let connectorToolset = try container.decodeIfPresent(
      ConnectorToolset?.self, forKey: .connectorToolset)
    {
      try toolsetTypeCheckAndSet(.connectorToolset(connectorToolset))
    }
    self.toolsetType = toolsetType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.timeout, forKey: .timeout)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.executionType, forKey: .executionType)
    try container.encodeIfPresent(self.toolFakeConfig, forKey: .toolFakeConfig)

    if let choice = self.toolsetType {
      switch choice {
      case .mcpToolset(let value):
        try container.encode(value, forKey: .mcpToolset)
      case .openApiToolset(let value):
        try container.encode(value, forKey: .openApiToolset)
      case .connectorToolset(let value):
        try container.encode(value, forKey: .connectorToolset)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of the toolset.
  public enum OneOf_ToolsetType: Codable, Equatable, Sendable {
    /// Optional. A toolset that contains a list of tools that are offered by the
    /// MCP server.
    indirect case mcpToolset(McpToolset?)
    /// Optional. A toolset that contains a list of tools that are defined by an
    /// OpenAPI schema.
    indirect case openApiToolset(OpenApiToolset?)
    /// Optional. A toolset that generates tools from an Integration Connectors
    /// Connection.
    indirect case connectorToolset(ConnectorToolset?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.Toolset"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
