// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A tool represents an action that the CES agent can take to achieve certain
/// goals.
public struct Tool: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the tool. Format:
  ///
  /// * `projects/{project}/locations/{location}/apps/{app}/tools/{tool}`
  ///   for standalone tools.
  /// * `projects/{project}/locations/{location}/apps/{app}/toolsets/{toolset}/tools/{tool}`
  ///   for tools retrieved from a toolset.
  ///
  /// These tools are dynamic and output-only; they cannot be referenced directly
  /// where a tool is expected.
  public var name: Swift.String = Swift.String()

  /// Output only. The display name of the tool, derived based on the tool's
  /// type. For example, display name of a [ClientFunction][Tool.ClientFunction]
  /// is derived from its `name` property.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The execution type of the tool.
  public var executionType: ExecutionType = ExecutionType()

  /// Optional. The timeout for the tool execution. If not set, the default
  /// timeout is 30 seconds for `SYNCHRONOUS` tools and 60 seconds for
  /// `ASYNCHRONOUS` tools.
  public var timeout: GoogleCloudWkt.Duration? = nil

  /// Output only. Timestamp when the tool was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Timestamp when the tool was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Etag used to ensure the object hasn't changed during a read-modify-write
  /// operation. If the etag is empty, the update will overwrite any concurrent
  /// changes.
  public var etag: Swift.String = Swift.String()

  /// Output only. If the tool is generated by the LLM assistant, this field
  /// contains a descriptive summary of the generation.
  public var generatedSummary: Swift.String = Swift.String()

  /// Optional. Configuration for tool behavior in fake mode.
  public var toolFakeConfig: ToolFakeConfig? = nil

  /// The type of the tool.
  public var toolType: OneOf_ToolType? = nil

  /// Initialize a new instance of `Tool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Tool().with { $0.clientFunction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case clientFunction = "clientFunction"
    case openApiTool = "openApiTool"
    case googleSearchTool = "googleSearchTool"
    case connectorTool = "connectorTool"
    case dataStoreTool = "dataStoreTool"
    case pythonFunction = "pythonFunction"
    case mcpTool = "mcpTool"
    case fileSearchTool = "fileSearchTool"
    case systemTool = "systemTool"
    case agentTool = "agentTool"
    case widgetTool = "widgetTool"
    case remoteAgentTool = "remoteAgentTool"
    case name = "name"
    case displayName = "displayName"
    case executionType = "executionType"
    case timeout = "timeout"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case etag = "etag"
    case generatedSummary = "generatedSummary"
    case toolFakeConfig = "toolFakeConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.executionType = try container.decode(ExecutionType.self, forKey: .executionType)
    self.timeout = try container.decodeIfPresent(GoogleCloudWkt.Duration.self, forKey: .timeout)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)
    self.generatedSummary = try container.decode(Swift.String.self, forKey: .generatedSummary)
    self.toolFakeConfig = try container.decodeIfPresent(
      ToolFakeConfig.self, forKey: .toolFakeConfig)

    var toolType: OneOf_ToolType? = nil
    let toolTypeCheckAndSet = {
      if toolType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'toolType'"))
      }
      toolType = $0
    }
    if let clientFunction = try container.decodeIfPresent(
      ClientFunction?.self, forKey: .clientFunction)
    {
      try toolTypeCheckAndSet(.clientFunction(clientFunction))
    }
    if let openApiTool = try container.decodeIfPresent(OpenApiTool?.self, forKey: .openApiTool) {
      try toolTypeCheckAndSet(.openApiTool(openApiTool))
    }
    if let googleSearchTool = try container.decodeIfPresent(
      GoogleSearchTool?.self, forKey: .googleSearchTool)
    {
      try toolTypeCheckAndSet(.googleSearchTool(googleSearchTool))
    }
    if let connectorTool = try container.decodeIfPresent(
      ConnectorTool?.self, forKey: .connectorTool)
    {
      try toolTypeCheckAndSet(.connectorTool(connectorTool))
    }
    if let dataStoreTool = try container.decodeIfPresent(
      DataStoreTool?.self, forKey: .dataStoreTool)
    {
      try toolTypeCheckAndSet(.dataStoreTool(dataStoreTool))
    }
    if let pythonFunction = try container.decodeIfPresent(
      PythonFunction?.self, forKey: .pythonFunction)
    {
      try toolTypeCheckAndSet(.pythonFunction(pythonFunction))
    }
    if let mcpTool = try container.decodeIfPresent(McpTool?.self, forKey: .mcpTool) {
      try toolTypeCheckAndSet(.mcpTool(mcpTool))
    }
    if let fileSearchTool = try container.decodeIfPresent(
      FileSearchTool?.self, forKey: .fileSearchTool)
    {
      try toolTypeCheckAndSet(.fileSearchTool(fileSearchTool))
    }
    if let systemTool = try container.decodeIfPresent(SystemTool?.self, forKey: .systemTool) {
      try toolTypeCheckAndSet(.systemTool(systemTool))
    }
    if let agentTool = try container.decodeIfPresent(AgentTool?.self, forKey: .agentTool) {
      try toolTypeCheckAndSet(.agentTool(agentTool))
    }
    if let widgetTool = try container.decodeIfPresent(WidgetTool?.self, forKey: .widgetTool) {
      try toolTypeCheckAndSet(.widgetTool(widgetTool))
    }
    if let remoteAgentTool = try container.decodeIfPresent(
      RemoteAgentTool?.self, forKey: .remoteAgentTool)
    {
      try toolTypeCheckAndSet(.remoteAgentTool(remoteAgentTool))
    }
    self.toolType = toolType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.executionType, forKey: .executionType)
    try container.encode(self.timeout, forKey: .timeout)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.generatedSummary, forKey: .generatedSummary)
    try container.encode(self.toolFakeConfig, forKey: .toolFakeConfig)

    if let choice = self.toolType {
      switch choice {
      case .clientFunction(let value):
        try container.encode(value, forKey: .clientFunction)
      case .openApiTool(let value):
        try container.encode(value, forKey: .openApiTool)
      case .googleSearchTool(let value):
        try container.encode(value, forKey: .googleSearchTool)
      case .connectorTool(let value):
        try container.encode(value, forKey: .connectorTool)
      case .dataStoreTool(let value):
        try container.encode(value, forKey: .dataStoreTool)
      case .pythonFunction(let value):
        try container.encode(value, forKey: .pythonFunction)
      case .mcpTool(let value):
        try container.encode(value, forKey: .mcpTool)
      case .fileSearchTool(let value):
        try container.encode(value, forKey: .fileSearchTool)
      case .systemTool(let value):
        try container.encode(value, forKey: .systemTool)
      case .agentTool(let value):
        try container.encode(value, forKey: .agentTool)
      case .widgetTool(let value):
        try container.encode(value, forKey: .widgetTool)
      case .remoteAgentTool(let value):
        try container.encode(value, forKey: .remoteAgentTool)
      }
    }
  }

  /// The type of the tool.
  public enum OneOf_ToolType: Codable, Equatable, Sendable {
    /// Optional. The client function.
    indirect case clientFunction(ClientFunction?)
    /// Optional. The open API tool.
    indirect case openApiTool(OpenApiTool?)
    /// Optional. The google search tool.
    indirect case googleSearchTool(GoogleSearchTool?)
    /// Optional. The Integration Connector tool.
    indirect case connectorTool(ConnectorTool?)
    /// Optional. The data store tool.
    indirect case dataStoreTool(DataStoreTool?)
    /// Optional. The python function tool.
    indirect case pythonFunction(PythonFunction?)
    /// Optional. The MCP tool. An MCP tool cannot be created or updated directly
    /// and is managed by the MCP toolset.
    indirect case mcpTool(McpTool?)
    /// Optional. The file search tool.
    indirect case fileSearchTool(FileSearchTool?)
    /// Optional. The system tool.
    indirect case systemTool(SystemTool?)
    /// Optional. The agent tool.
    indirect case agentTool(AgentTool?)
    /// Optional. The widget tool.
    indirect case widgetTool(WidgetTool?)
    /// Optional. The remote agent tool.
    indirect case remoteAgentTool(RemoteAgentTool?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.Tool"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
