// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Rule for transferring to a specific agent.
public struct TransferRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the child agent the rule applies to.
  /// Format:
  /// `projects/{project}/locations/{location}/apps/{app}/agents/{agent}`
  public var childAgent: Swift.String = Swift.String()

  /// Required. The direction of the transfer.
  public var direction: TransferRule.Direction = TransferRule.Direction()

  /// The rule type.
  public var ruleType: OneOf_RuleType? = nil

  /// Initialize a new instance of `TransferRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferRule().with { $0.deterministicTransfer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case deterministicTransfer = "deterministicTransfer"
    case disablePlannerTransfer = "disablePlannerTransfer"
    case childAgent = "childAgent"
    case direction = "direction"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.childAgent = try container.decode(Swift.String.self, forKey: .childAgent)
    self.direction = try container.decode(TransferRule.Direction.self, forKey: .direction)

    var ruleType: OneOf_RuleType? = nil
    let ruleTypeCheckAndSet = {
      if ruleType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'ruleType'"))
      }
      ruleType = $0
    }
    if let deterministicTransfer = try container.decodeIfPresent(
      TransferRule.DeterministicTransfer?.self, forKey: .deterministicTransfer)
    {
      try ruleTypeCheckAndSet(.deterministicTransfer(deterministicTransfer))
    }
    if let disablePlannerTransfer = try container.decodeIfPresent(
      TransferRule.DisablePlannerTransfer?.self, forKey: .disablePlannerTransfer)
    {
      try ruleTypeCheckAndSet(.disablePlannerTransfer(disablePlannerTransfer))
    }
    self.ruleType = ruleType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.childAgent, forKey: .childAgent)
    try container.encode(self.direction, forKey: .direction)

    if let choice = self.ruleType {
      switch choice {
      case .deterministicTransfer(let value):
        try container.encode(value, forKey: .deterministicTransfer)
      case .disablePlannerTransfer(let value):
        try container.encode(value, forKey: .disablePlannerTransfer)
      }
    }
  }

  /// Deterministic transfer rule. When the condition evaluates to true, the
  /// transfer occurs.
  public struct DeterministicTransfer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The condition to evaluate.
    public var conditionType: OneOf_ConditionType? = nil

    /// Initialize a new instance of `DeterministicTransfer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeterministicTransfer().with { $0.expressionCondition = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case expressionCondition = "expressionCondition"
      case pythonCodeCondition = "pythonCodeCondition"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var conditionType: OneOf_ConditionType? = nil
      let conditionTypeCheckAndSet = {
        if conditionType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'conditionType'"))
        }
        conditionType = $0
      }
      if let expressionCondition = try container.decodeIfPresent(
        ExpressionCondition?.self, forKey: .expressionCondition)
      {
        try conditionTypeCheckAndSet(.expressionCondition(expressionCondition))
      }
      if let pythonCodeCondition = try container.decodeIfPresent(
        PythonCodeCondition?.self, forKey: .pythonCodeCondition)
      {
        try conditionTypeCheckAndSet(.pythonCodeCondition(pythonCodeCondition))
      }
      self.conditionType = conditionType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.conditionType {
        switch choice {
        case .expressionCondition(let value):
          try container.encode(value, forKey: .expressionCondition)
        case .pythonCodeCondition(let value):
          try container.encode(value, forKey: .pythonCodeCondition)
        }
      }
    }

    /// The condition to evaluate.
    public enum OneOf_ConditionType: Codable, Equatable, Sendable {
      /// Optional. A rule that evaluates a session state condition.
      /// If the condition evaluates to true, the transfer occurs.
      indirect case expressionCondition(ExpressionCondition?)
      /// Optional. A rule that uses Python code block to evaluate the
      /// conditions. If the condition evaluates to true, the transfer occurs.
      indirect case pythonCodeCondition(PythonCodeCondition?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.TransferRule.DeterministicTransfer"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A rule that prevents the planner from transferring to the target agent.
  public struct DisablePlannerTransfer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. If the condition evaluates to true, planner will not be allowed
    /// to transfer to the target agent.
    public var expressionCondition: ExpressionCondition? = nil

    /// Initialize a new instance of `DisablePlannerTransfer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DisablePlannerTransfer().with { $0.expressionCondition = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ces.v1.TransferRule.DisablePlannerTransfer"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The direction of the transfer.
  public enum Direction: Codable, Equatable, Sendable {
    /// Unspecified direction.
    case unspecified
    /// Transfer from the parent agent to the child agent.
    case parentToChild
    /// Transfer from the child agent to the parent agent.
    case childToParent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .parentToChild: return 1
      case .childToParent: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DIRECTION_UNSPECIFIED"
      case .parentToChild: return "PARENT_TO_CHILD"
      case .childToParent: return "CHILD_TO_PARENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Direction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DIRECTION_UNSPECIFIED": self = .unspecified
      case "PARENT_TO_CHILD": self = .parentToChild
      case "CHILD_TO_PARENT": self = .childToParent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Direction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .parentToChild
      case 2: self = .childToParent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .parentToChild: return try container.encode(1)
      case .childToParent: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The rule type.
  public enum OneOf_RuleType: Codable, Equatable, Sendable {
    /// Optional. A rule that immediately transfers to the target agent when the
    /// condition is met.
    indirect case deterministicTransfer(TransferRule.DeterministicTransfer?)
    /// Optional. Rule that prevents the planner from transferring to the target
    /// agent.
    indirect case disablePlannerTransfer(TransferRule.DisablePlannerTransfer?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ces.v1.TransferRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
